services:

  api:
    git_url: https://github.com/MiriEngel/docker.git
    git_branch: master
    command: npm start
    build_root: .
    ports:
      - container: 8080
        http: 80
        https: 443
    env_vars:
      NODE_ENV: development

databases:
  - mongodb
